<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@907.v6713a_ed8a_573">
  <node class="cps.n.StepEndNode" plugin="workflow-cps@3903.v48a_8836749e9">
    <parentIds>
      <string>40</string>
    </parentIds>
    <id>41</id>
    <startId>37</startId>
  </node>
  <actions>
    <wf.a.TimingAction plugin="workflow-api@1316.v33eb_726c50b_a_">
      <startTime>1718676885763</startTime>
    </wf.a.TimingAction>
    <wf.a.ErrorAction plugin="workflow-api@1316.v33eb_726c50b_a_">
      <error class="hudson.AbortException">
        <detailMessage>script returned exit code 1</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:668)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:614)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:555)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(Unknown Source)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)</trace>
          <trace>java.base/java.lang.Thread.run(Unknown Source)</trace>
        </stackTrace>
        <suppressedExceptions>
          <wf.a.ErrorAction_-ErrorId>
            <stackTrace/>
            <suppressedExceptions class="empty-list"/>
            <uuid>bcdd9e75-e5ee-49ce-87b9-d09f77385d47</uuid>
          </wf.a.ErrorAction_-ErrorId>
        </suppressedExceptions>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>